version: "3.7"
services:
  postgresql:
    image: postgres:16
    container_name: postgresql
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    restart: always
    user: root
    ports:
      - "5432:5432"
    volumes:
      - ./docker/initdb:/docker-entrypoint-initdb.d
  php:
    container_name: php
    build:
      context: ./app
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/html
      - ./apache/httpd.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - postgresql

volumes:
  postgres_data:
